version: "2.1"
orbs:
    android: circleci/android@1.0.3
    flutter: circleci/flutter@2.0.0
jobs:
    distribute:
        executor:
            name: android/android-machine
        steps:
            - checkout
            - flutter/install_sdk_and_pub:
                version: 3.0.3
            - run:
                command: flutter pub get
workflows:
    distribute:
        jobs:
            - distribute